<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<project default="Distribute" name="Build and Distribute Maestro and ABC Player">
	<property name="src" value="../src" />
	<property name="target" value="../target" />
	<property name="audio" value="../audio" />
	<property name="audio_backslash" value="..\audio" />
	<property name="output" value="output" />
	<property name="build" value="build" />
	<property name="tools" location="tools" />
	<property name="basename.AbcPlayer" value="AbcPlayer" />
	<property name="basename.Maestro" value="Maestro" />
	<property name="basename.AbcTools" value="AbcTools" />
	<property file="${src}/com/digero/abcplayer/version.txt" />
	<!-- For version.AbcPlayer -->
	<property file="${src}/com/digero/maestro/version.txt" />
	<!-- For version.Maestro -->
	<property name="version.AbcTools" value="${version.AbcPlayer}" />
	<condition property="isWindows">
		<os family="windows" />
	</condition>
	<property environment="env"/><!-- will fetch all the system environment variables and prefix them with env. -->

	<condition property="isUnix">
		<os family="unix" />
	</condition>

	<target name="-mvn_windows" if="isWindows" description="Maven clean and compile (Windows)">
		<exec dir=".." executable="cmd" failonerror="true">
			<arg line="/c mvn clean install" />
		</exec>
	</target>

	<target name="-mvn_unix" if="isUnix" description="Maven clean and compile (Linux)">
		<exec dir=".." executable="sh" failonerror="true">
			<arg line="-c 'mvn clean install'" />
		</exec>
	</target>

	<target name="Clean" description="Clean build folder">
		<delete dir="${build}" />
	</target>

	<target name="-CopyThings" depends="-mvn_windows, -mvn_unix" description="Copy icons,jars and txt files to build folder">
		<mkdir dir="${build}" />
		<delete>
			<fileset dir="${build}" includes="*.log" />
		</delete>
		<copy file="abcfile.ico" todir="${build}" />
		<copy file="abcplaylist.ico" todir="${build}" />
		<copy file="midifile.ico" todir="${build}" />
		<copy file="msxfile.ico" todir="${build}" />
		<!--<copy file="Start Maestro.bat" todir="${build}" />
		<copy file="Start AbcPlayer.bat" todir="${build}" />
		<copy file="Start ABC Tools.bat" todir="${build}" />-->
		<copy file="Changes since Maestro 2.5.0.txt" todir="${build}" />
		<!--copy todir="${build}">
			<fileset dir="${target}" includes="*.jar" />
		</copy-->
		<!--		<copy todir="${target}/com/digero/maestro">
			<fileset dir="${src}/com/digero/maestro" includes="*.txt" />
		</copy>
		<copy todir="${target}/com/digero/common/midi">
			<fileset dir="${src}/com/digero/common/midi" includes="*.txt" />
		</copy>
		<copy todir="${target}/com/digero/abcplayer">
			<fileset dir="${src}/com/digero/abcplayer" includes="*.txt" />
		</copy>
		<copy todir="${target}/com/digero/common/icons">
			<fileset dir="${src}/com/digero/common/icons" includes="*.png" />
		</copy>-->
	</target>

	<target name="-GenerateSoundFontInfo.CheckUpToDate" description="Test if LotroInstruments.txt needs making">
		<uptodate property="GenerateSoundFontInfo.uptodate" value="true" targetfile="${basedir}/${audio}/LotroInstruments/LotroInstruments.txt">
			<srcfiles dir="${src}/com/digero/tools/soundfont/" />
			<srcfiles file="${src}/com/digero/common/abc/LotroInstrument.java" />
			<!-- Since classes are rebuilt every run, we check against the src files instead -->
		</uptodate>
		<echo message="GenerateSoundFontInfo.uptodate is now ${GenerateSoundFontInfo.uptodate}."/>
	</target>
	
	<target name="-GenerateSoundFontInfo" depends="-GenerateSoundFontInfo.CheckUpToDate" unless="GenerateSoundFontInfo.uptodate" description="Make LotroInstruments.txt">
		<java classname="com.digero.tools.soundfont.GenerateSoundFontInfo" classpath="${target}/classes" fork="yes" failonerror="yes">
			<arg value="${basedir}/${audio}/LotroInstruments" />
			<arg value="${basedir}/${audio}/LotroInstruments/LotroInstruments.txt" />
		</java>
	</target>

	<target name="-LotroInstruments.CheckUpToDate" description="Test if SF2 needs making">
		<uptodate property="LotroInstruments.uptodate" value="true" targetfile="${build}/LotroInstruments.sf2">
			<srcfiles dir="${basedir}/${audio}/LotroInstruments" />
		</uptodate>
		<echo message="LotroInstruments.uptodate is now ${LotroInstruments.uptodate}."/>
	</target>

	<target name="-LotroInstrumentsOld" depends="-GenerateSoundFontInfo,-LotroInstruments.CheckUpToDate" unless="LotroInstruments.uptodate" description="Make SF2 file">
		<exec executable="${tools}/sf2comp.exe" failonerror="true"><!--  error="sf2comp_err.txt" output="sf2comp_out.txt" -->
			<arg value="c" /><!-- compile -->
			<arg value="-m" /><!-- mute (suppress output) -->
			<arg value="-i" />
			<arg value="${audio_backslash}\LotroInstruments\LotroInstruments.txt" />
			<arg value="${build}\LotroInstruments.sf2" />
		</exec>
	</target>
	
	<target name="LotroInstruments" description="Copy SF2 file">
		<copy file="LotroInstruments.sf2" todir="${build}" />
	</target>

	<target name="Build" depends="-CopyThings,LotroInstruments" description="Make all except ZIP and MSI files"/>

	<target name="-JPackageAppImages" depends="Build" description="Make folders with exe and runtimes for all 3 apps">
		<echo>JAVA_HOME=${env.JAVA_HOME}</echo>
		<delete dir="${build}/jpackage" />
		<delete dir="${build}/staging" />
		<mkdir dir="${build}/staging" />
		<copy file="${target}/Maestro.jar" todir="${build}/staging" />
		<copy file="${target}/AbcPlayer.jar" todir="${build}/staging" />
		<copy file="${target}/AbcTools.jar" todir="${build}/staging" />
		<!-- Abc Player -->
		<exec executable="${env.JAVA_HOME}/bin/jpackage.exe" failonerror="true">
			<env key="PATH" path="${tools}/wix"/>
			<arg value="--type"/>
			<arg value="app-image"/> <!-- "app-image" for just making a folder with the exe -->
			<arg value="--app-version"/>
			<arg value="${version.AbcPlayer}"/>
			<arg value="--description"/>
			<arg value="ABC Player for the Lord of the Rings Online"/>
			<arg value="--vendor"/>
			<arg value="Elamond and Aifel"/>
			<arg value="--icon"/>
			<arg value="abcplayer.ico"/>
			<arg value="--java-options"/>
			<arg value="--enable-native-access=ALL-UNNAMED"/>
			<arg value="--java-options"/>
			<arg value="--add-exports=java.desktop/com.sun.media.sound=ALL-UNNAMED"/>
<!--			<arg value="&#45;&#45;java-options"/>-->
<!--			<arg value="-Dsun.java2d.opengl=True"/>-->
			<arg value="--dest"/>
			<arg value="${build}/jpackage/"/>
			<arg value="--input"/>
			<arg value="${build}/staging"/>
			<arg value="--name"/>
			<arg value="AbcPlayer"/>
			<arg value="--main-class"/>
			<arg value="com.digero.abcplayer.AbcPlayer"/>
			<arg value="--main-jar"/>
			<arg value="AbcPlayer.jar"/>
		</exec>
		<!-- Abc Tools -->
		<exec executable="${env.JAVA_HOME}/bin/jpackage.exe" failonerror="true">
			<env key="PATH" path="${tools}/wix"/>
			<arg value="--type"/>
			<arg value="app-image"/>
			<arg value="--app-version"/>
			<arg value="${version.AbcTools}"/>
			<arg value="--description"/>
			<arg value="ABC tools to merge abc files or auto export abc"/>
			<arg value="--vendor"/>
			<arg value="Aifel and Elamond"/>
			<arg value="--icon"/>
			<arg value="abctools.ico"/>
			<arg value="--java-options"/>
			<arg value="--enable-native-access=ALL-UNNAMED"/>
			<arg value="--java-options"/>
			<arg value="--add-exports=java.desktop/com.sun.media.sound=ALL-UNNAMED"/>
<!--			<arg value="&#45;&#45;java-options"/>-->
<!--			<arg value="-Dsun.java2d.opengl=True"/>-->
			<arg value="--dest"/>
			<arg value="${build}/jpackage/"/>
			<arg value="--input"/>
			<arg value="${build}/staging"/>
			<arg value="--name"/>
			<arg value="AbcTools"/>
			<arg value="--main-class"/>
			<arg value="com.aifel.abctools.AbcTools"/>
			<arg value="--main-jar"/>
			<arg value="AbcTools.jar"/>
		</exec>
		<!-- Copy assets for final app/ folder -->
		<copy file="${build}/LotroInstruments.sf2" todir="${build}/staging" />
		<copy file="${build}/abcfile.ico" todir="${build}/staging" />
		<copy file="${build}/abcplaylist.ico" todir="${build}/staging" />
		<copy file="${build}/midifile.ico" todir="${build}/staging" />
		<copy file="${build}/msxfile.ico" todir="${build}/staging" />
		<!-- Maestro -->
		<exec executable="${env.JAVA_HOME}/bin/jpackage.exe" failonerror="true">
			<env key="PATH" path="${tools}/wix"/>
			<arg value="--type"/>
			<arg value="app-image"/> <!-- "app-image" for just making a folder with the exe -->
			<arg value="--app-version"/>
			<arg value="${version.Maestro}"/>
			<arg value="--description"/>
			<arg value="Maestro MIDI to ABC converter"/>
			<arg value="--vendor"/>
			<arg value="Aifel and Elamond"/>
			<arg value="--icon"/>
			<arg value="maestro.ico"/>
			<arg value="--java-options"/>
			<arg value="--enable-native-access=ALL-UNNAMED"/>
			<arg value="--java-options"/>
			<arg value="--add-exports=java.desktop/com.sun.media.sound=ALL-UNNAMED"/>
<!--			<arg value="&#45;&#45;java-options"/>-->
<!--			<arg value="-Dsun.java2d.opengl=True"/>-->
			<arg value="--dest"/>
			<arg value="${build}/jpackage/"/>
			<arg value="--input"/>
			<arg value="${build}/staging"/>
			<arg value="--name"/>
			<arg value="Maestro"/>
			<arg value="--main-class"/>
			<arg value="com.digero.maestro.MaestroMain"/>
			<arg value="--main-jar"/>
			<arg value="Maestro.jar"/>
		</exec>
		<copy file="${build}/jpackage/AbcPlayer/app/AbcPlayer.cfg" tofile="${build}/jpackage/Maestro/app/AbcPlayer.cfg" />
		<copy file="${build}/jpackage/AbcTools/app/AbcTools.cfg" tofile="${build}/jpackage/Maestro/app/AbcTools.cfg" />
		<copy file="${build}/jpackage/AbcPlayer/AbcPlayer.exe" tofile="${build}/AbcPlayer.exe" />
		<copy file="${build}/jpackage/AbcTools/AbcTools.exe" tofile="${build}/AbcTools.exe" />
		<copy file="${build}/jpackage/Maestro/Maestro.exe" tofile="${build}/Maestro.exe" />
		<copy todir="${build}/app">
			<fileset dir="${build}/jpackage/Maestro/app" />
		</copy>
		<copy todir="${build}/runtime">
			<fileset dir="${build}/jpackage/Maestro/runtime" />
		</copy>
<!--		<delete dir="${build}/jpackage" />-->
	</target>
	
	<target name="-JPackageToolsMSI" description="Make Beta MSI for AbcTools">
		<mkdir dir="${build}/jpackageTools" />
		<copy file="Changes since Maestro 2.5.0.txt" todir="${build}/jpackageTools" />
		<copy file="${build}/AbcTools.jar" todir="${build}/jpackageTools" />
	    <exec executable="${env.JAVA_HOME}/bin/jpackage.exe" failonerror="true">
	    	<env key="PATH" path="${tools}/wix"/>
	    	<arg value="--type"/>
	    	<arg value="msi"/>
	    	<arg value="--app-version"/>
	    	<arg value="${version.AbcTools}"/>
	    	<arg value="--description"/>
    		<arg value="ABC tools to merge abc files or auto export abc"/>
	    	<arg value="--vendor"/>
	    	<arg value="Aifel and Elamond"/>
    		<arg value="--icon"/>
    		<arg value="abctools.ico"/>
	    	<arg value="--java-options"/>
	    	<arg value="--enable-native-access=ALL-UNNAMED"/>
	    	<arg value="--java-options"/>
	    	<arg value="--add-exports=java.desktop/com.sun.media.sound=ALL-UNNAMED"/>
	    	<arg value="--java-options"/>
	    	<arg value="-Dsun.java2d.opengl=True"/>
    		<arg value="--dest"/>
	    	<arg value="${output}"/>
	    	<arg value="--input"/>
	    	<arg value="${build}/jpackageTools"/>
	    	<arg value="--name"/>
	    	<arg value="AbcTools-BETA"/>
	    	<arg value="--main-class"/>
	    	<arg value="com.aifel.abctools.AbcTools"/>
	    	<arg value="--main-jar"/>
	    	<arg value="AbcTools.jar"/>
	    </exec>
		<delete dir="${build}/jpackageTools" />
	</target>
	
	<target name="-JPackagePlayerMSI" description="Make Beta MSI for Abc Player">
		<mkdir dir="${build}/jpackagePlayer" />
		<copy file="Changes since Maestro 2.5.0.txt" todir="${build}/jpackagePlayer" />
		<copy file="${build}/AbcPlayer.jar" todir="${build}/jpackagePlayer" />
		<copy file="${build}/LotroInstruments.sf2" todir="${build}/jpackagePlayer" />
	    <exec executable="${env.JAVA_HOME}/bin/jpackage.exe" failonerror="true">
	    	<env key="PATH" path="${tools}/wix"/>
	    	<arg value="--type"/>
	    	<arg value="msi"/>
	    	<arg value="--app-version"/>
	    	<arg value="${version.AbcPlayer}"/>
	    	<arg value="--description"/>
    		<arg value="ABC Player for the Lord of the Rings Online"/>
	    	<arg value="--vendor"/>
	    	<arg value="Elamond and Aifel"/>
    		<arg value="--icon"/>
    		<arg value="abcplayer.ico"/>
	    	<arg value="--java-options"/>
	    	<arg value="--enable-native-access=ALL-UNNAMED"/>
	    	<arg value="--java-options"/>
	    	<arg value="--add-exports=java.desktop/com.sun.media.sound=ALL-UNNAMED"/>
	    	<arg value="--java-options"/>
	    	<arg value="-Dsun.java2d.opengl=True"/>
    		<arg value="--dest"/>
	    	<arg value="${output}"/>
	    	<arg value="--input"/>
	    	<arg value="${build}/jpackagePlayer"/>
	    	<arg value="--name"/>
	    	<arg value="AbcPlayer-BETA"/>
	    	<arg value="--main-class"/>
	    	<arg value="com.digero.abcplayer.AbcPlayer"/>
	    	<arg value="--main-jar"/>
	    	<arg value="AbcPlayer.jar"/>
	    </exec>
		<delete dir="${build}/jpackagePlayer" />
	</target>
	
	<target name="-JPackageMaestroMSI" description="Make Beta MSI for Maestro">
		<mkdir dir="${build}/jpackageMaestro" />
		<copy file="Changes since Maestro 2.5.0.txt" todir="${build}/jpackageMaestro" />
		<copy file="${build}/Maestro.jar" todir="${build}/jpackageMaestro" />
		<copy file="${build}/LotroInstruments.sf2" todir="${build}/jpackageMaestro" />
	    <exec executable="${env.JAVA_HOME}/bin/jpackage.exe" failonerror="true">
	    	<env key="PATH" path="${tools}/wix"/>
	    	<arg value="--type"/>
	    	<arg value="msi"/> <!-- "app-image" for just making a folder with the exe -->
	    	<arg value="--win-console"/><!-- with this, it outputs to console if started from that -->
	    	<arg value="--app-version"/>
	    	<arg value="${version.Maestro}"/>
	    	<arg value="--description"/>
    		<arg value="Maestro MIDI to ABC converter"/>
	    	<arg value="--vendor"/>
	    	<arg value="Aifel and Elamond"/>
    		<arg value="--icon"/>
    		<arg value="maestro.ico"/>
	    	<arg value="--java-options"/>
	    	<arg value="--enable-native-access=ALL-UNNAMED"/>
	    	<arg value="--java-options"/>
	    	<arg value="--add-exports=java.desktop/com.sun.media.sound=ALL-UNNAMED"/>
	    	<arg value="--java-options"/>
	    	<arg value="-Dsun.java2d.opengl=True"/>
    		<arg value="--dest"/>
	    	<arg value="${output}"/>
	    	<arg value="--input"/>
	    	<arg value="${build}/jpackageMaestro"/>
	    	<arg value="--name"/>
	    	<arg value="Maestro-BETA"/>
	    	<arg value="--main-class"/>
	    	<arg value="com.digero.maestro.MaestroMain"/>
	    	<arg value="--main-jar"/>
	    	<arg value="Maestro.jar"/>
	    </exec>
		<delete dir="${build}/jpackageMaestro" />
	</target>
	
	<target name="-Wix-Cop" description="Runs WiX cop to fix errors in wix project">
	    <exec executable="${tools}/wix/WixCop.exe" failonerror="false">
	    	<arg value="-f"/> <!-- fix errors -->
	        <arg value="MaestroInstaller.wix"/>
	    </exec>
	</target>
	
	<target name="-Wix-Runtime" description="Runs WiX Heat to harvest all runtime files">
		<!-- Run heat on runtime directory -->
		<exec executable="${tools}/wix/heat.exe" failonerror="true">
			<arg value="dir"/>  <!-- Specifies that a directory will be harvested -->
			<arg value="${build}/runtime"/>  <!-- Copies files in the Maestro subfolder -->
			<arg value="-cg"/>  <!-- Defines a component group to group harvested files -->
			<arg value="j24RuntimeComponentGroup"/>  <!-- Names the component group  -->
			<arg value="-dr"/>  <!-- Specifies the directory reference ID -->
			<arg value="RuntimeDir"/>  <!-- Names the directory reference -->
			<arg value="-srd"/>  <!-- Suppresses the harvesting of the root directory itself, keeping only its contents -->
			<arg value="-var"/>  <!-- Allows the directory to be referenced using a variable instead of an absolute path -->
			<arg value="var.j24runtime"/>  <!-- Defines the variable name for referencing the harvested directory -->
			<arg value="-gg"/> <!-- generate GUIDs -->
			<arg value="-sreg"/> <!-- don't harvest DLL info from registry -->
			<arg value="-scom"/> <!-- don't harvest COM info from registry -->
			<arg value="-out"/>  <!-- Specifies the output file where harvested WiX XML will be stored -->
			<arg value="runtime.wxs"/>  <!-- Saves the harvested files as "runtime.wxs" -->
		</exec>
	</target>
	
	<target name="Installer" depends="Build,-JPackageAppImages,-Wix-Runtime" if="isWindows" description="Make MSI file">
		<mkdir dir="${output}" />
		<property name="msipath" location="${output}/${basename.Maestro}_v${version.Maestro}.msi" />
		<echo>Building msi: ${msipath}</echo>
		<exec executable="${tools}/wix/candle.exe" failonerror="true">
			<arg value="-nologo" />
			<arg value="-arch" />
			<arg value="x64" />
			<arg value="-dMaestroVersion=${version.Maestro}" />
			<arg value="-dAbcPlayerVersion=${version.AbcPlayer}" />
			<arg value="-dAbcToolsVersion=${version.AbcTools}" />
			<arg value="-dbuild=${build}" />
			<arg value="-dj24runtime=${build}/runtime" />
			<arg value="-out" />
			<arg value="${build}/" />
			<arg value="MaestroInstaller.wix" />
			<arg value="runtime.wxs" />
		</exec>
		<exec executable="${tools}/wix/light.exe" failonerror="true">
			<arg value="-nologo" />
			<!--arg value="-sval" /--><!-- suppress ICE validation, needed to not need to run light as admin -->
			<arg value="-sw1076" />
			<!-- Installer removes version numbers equal to itself -->
			<arg value="-ext" />
			<arg value="WixUIExtension" />
			<arg value="-loc" />
			<arg value="MaestroInstallerStrings.wxl" />
			<arg value="-o" />
			<arg value="${output}/${basename.Maestro}_v${version.Maestro}.msi" />
			<arg value="-pdbout" />
			<arg value="${build}/MaestroInstaller.wixpdb" />
			<arg value="${build}/runtime.wixobj" />
			<arg value="${build}/MaestroInstaller.wixobj" />
		</exec>
	</target>

	<target name="ZipFile" depends="Build,-JPackageAppImages" description="Make ZIP file">
		<mkdir dir="${output}" />
		<zip destfile="${output}/${basename.Maestro}_v${version.Maestro}.zip" basedir="${build}">
			<zipfileset file="${build}/Maestro.exe" fullpath="Maestro.exe" />
			<zipfileset file="${build}/AbcPlayer.exe" fullpath="AbcPlayer.exe" />
			<zipfileset file="${build}/AbcTools.exe" fullpath="AbcTools.exe"/>
			<include name="Changes since Maestro 2.5.0.txt" />
			<zipfileset dir="${build}/app" prefix="app"/>
			<zipfileset dir="${build}/runtime" prefix="runtime"/>
			<zipfileset file="launch_maestro.sh" fullpath="linux_or_mac/linux_maestro.sh" filemode="755" />
			<zipfileset file="launch_abcplayer.sh" fullpath="linux_or_mac/linux_abcplayer.sh" filemode="755" />
			<zipfileset file="launch_abctools.sh" fullpath="linux_or_mac/linux_abctools.sh" filemode="755" />
			<zipfileset file="launch_maestro.sh" fullpath="linux_or_mac/mac_maestro.command" filemode="755" />
			<zipfileset file="launch_abcplayer.sh" fullpath="linux_or_mac/mac_abcplayer.command" filemode="755" />
			<zipfileset file="launch_abctools.sh" fullpath="linux_or_mac/mac_abctools.command" filemode="755" />
		</zip>
	</target>

	<target name="Distribute Beta" depends="Build,-JPackageToolsMSI,-JPackagePlayerMSI,-JPackageMaestroMSI" if="isWindows" description="Makes individual beta installers using JPackage"/>
	<target name="Distribute" depends="Installer,ZipFile" description="Make final ZIP and MSI files"/>
</project>
